STATUS_SCHEDULED = "SCHEDULED"
STATUS_CANCELLED = "CANCELLED"
STATUS_COMPLETED = "COMPLETED"

STATUS_CHOICES = [
    (STATUS_SCHEDULED, "Agendado"),
    (STATUS_CANCELLED, "Cancelado"),
    (STATUS_COMPLETED, "Realizado"),
]