# Generated by Django 3.2.3 on 2021-07-18 16:40

from django.db import migrations, models
import arrow
    
class Migration(migrations.Migration):

    dependencies = [
        ('calendario', '0002_auto_20210704_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attention_hours',
            name='day',
            field=models.CharField(choices=[('L', 'Lunes'), ('M', 'Martes'), ('X', 'Miercoles'), ('J', 'Jueves'), ('V', 'Viernes'), ('S', 'Sabado'), ('D', 'Domingo')], max_length=2),
        ), 
    ]
